# 文件存储路径
local:
  store: D:/Source/PicBed
# 日志级别
logging:
  level:
    com:
      reine:
        imagehost: debug
# mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  # sqlite数据库
  datasource:
    url: jdbc:sqlite:imgUrl.db