# 文件存储路径
local:
  store: pic-bed
spring:
  # sqlite数据库
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:imgUrl.db
  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/init.sql