# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  # 监听的端口号
  port: 8824
spring:
  application:
    ui:
      default-css: classpath:/css/default.css
      default-icon: classpath:/image/logo.png
  profiles:
    # 默认使用开发环境配置
    active: @profileActive@
  servlet:
    # 指定上传文件的最大大小
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB
  datasource:
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/init.sql
  threads:
    virtual:
      enabled: true
# web
web:
  base:
    path:
      image: image