name: Build Jar File
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  # 打包
  build-jar:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package -Pdetach --file pom.xml
      - name: Rename Jar Windows
        if: ${{ matrix.os == 'windows' }}
        run: .github/scripts/windows.ps1
      - name: Rename Jar Ubuntu
        if: ${{ matrix.os == 'ubuntu' }}
        run: bash .github/scripts/ubuntu.sh
      - name: Rename Jar Macos
        if: ${{ matrix.os == 'macos' }}
        run: bash .github/scripts/macos.sh
      - name: Upload Jar as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: LocalImageHost-${{ matrix.os }}
          path: target/*.jar
  # 发布
  release:
    runs-on: ubuntu-latest
    needs: build-jar
    permissions:
      contents: write
    steps:
      - name: Checkout the source
        uses: actions/checkout@v3
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: product
          pattern: LocalImageHost-*
          merge-multiple: true
      - name: List Directory
        run: ls -R product
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          body_path: .github/CHANGELOG.md
          draft: false
          fail_on_unmatched_files: true
          prerelease: false
          files: product/*.jar
